const { test, expect } = require('@playwright/test');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
const { execFileSync } = require('node:child_process');
const root = path.resolve(__dirname, '../..');
const output = fs.mkdtempSync(path.join(os.tmpdir(), 'owner-workspace-qa-'));
test.beforeAll(() => execFileSync(path.join(root, '.venv/bin/python'), ['-m', 'house_design', 'predesign', 'owner-workspace', '--output-root', output], { cwd: root }));
for (const width of [1440, 390]) {
  test(`offline owner draft roundtrip ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: width === 390 ? 844 : 900 });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
    await page.goto(pathToFileURL(path.join(output, 'owner-workspace.html')).href);
    page.on('dialog', dialog => dialog.accept());
    await expect(page).toHaveTitle('三棟屋主工作台');
    await expect(page.locator('#question-count')).toHaveText('顯示 8 項');
    const first = page.locator('#answer-list article:visible').first();
    await first.locator('[data-field="answer"]').fill('一樓要能完整生活，待家人討論');
    await expect(page.locator('#notice')).toContainText('請下載草稿');
    const promise = page.waitForEvent('download');
    await page.locator('#download').click();
    const download = await promise;
    const file = path.join(output, `draft-${width}.json`);
    await download.saveAs(file);
    const draft = JSON.parse(fs.readFileSync(file, 'utf8'));
    expect(draft.rows).toHaveLength(1);
    expect(draft.rows[0].data.answer).toContain('完整生活');
    const preview = JSON.parse(execFileSync(path.join(root, '.venv/bin/python'), ['-m', 'house_design', 'intake', 'owner-records-import', '--file', file], { cwd: root, encoding: 'utf8' }));
    expect(preview.mode).toBe('preview');
    expect(preview.count).toBe(1);
    await page.locator('#clear').click();
    await expect(page.locator('#answer-list article:visible').first().locator('[data-field="answer"]')).toHaveValue('');
    await page.locator('#load').setInputFiles(file);
    await expect(page.locator('#answer-list article:visible').first().locator('[data-field="answer"]')).toHaveValue('一樓要能完整生活，待家人討論');
    await page.locator('#due').selectOption('all');
    await expect(page.locator('#answer-list article:visible')).toHaveCount(105);
    await page.getByRole('button', { name: '房間需求卡', exact: true }).click();
    await expect(page.locator('#room-list article:visible')).toHaveCount(66);
    await page.locator('#building').selectOption('B');
    await page.locator('#floor').selectOption('floor-1');
    await expect(page.locator('#room-list article:visible').first()).toContainText('candidate');
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.getByRole('button', { name: '會議與變更', exact: true }).click();
    await page.locator('#add-meeting').click();
    await page.locator('#meeting-list [data-field="topic"]').fill('TEST ONLY / 神桌管線');
    await page.locator('#meeting-list [data-field="stage"]').selectOption('professional_pending');
    await page.locator('#add-change').click();
    await page.locator('#meeting-list [data-field="old"]').fill('TEST ONLY / 原配置');
    await page.getByRole('button', { name: '實物量測', exact: true }).click();
    await page.locator('#measurement-list [data-field="width_mm"]').fill('1260');
    await page.locator('#add-proposal').click();
    await page.locator('#proposal-list [data-field="label"]').fill('TEST ONLY / 神桌');
    await page.evaluate(() => { window.print = () => window.__printed = true; });
    await page.locator('#print').click();
    expect(await page.evaluate(() => window.__printed)).toBe(true);
    await page.screenshot({ path: path.join(os.tmpdir(), `house-owner-workspace-${width}.png`), fullPage: false });
    expect(errors).toEqual([]);
  });
}
test('bad draft load preserves edits and blocked cache is explained', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(window, 'localStorage', { get() { throw new Error('QA storage blocked'); } }));
  await page.goto(pathToFileURL(path.join(output, 'owner-workspace.html')).href);
  await expect(page.locator('#notice')).toContainText('暫存不可用');
  const input = page.locator('#answer-list article:visible').first().locator('[data-field="answer"]');
  await input.fill('TEST ONLY / 保留答案');
  await expect(page.locator('#notice')).toContainText('立即下載');
  await page.locator('#load').setInputFiles({ name: 'stale.json', mimeType: 'application/json', buffer: Buffer.from('{}') });
  await expect(page.locator('#notice')).toContainText('載入失敗');
  await expect(input).toHaveValue('TEST ONLY / 保留答案');
});
test('draft text is never rendered as HTML', async ({ page }) => {
  await page.goto(pathToFileURL(path.join(output, 'owner-workspace.html')).href);
  await page.getByRole('button', { name: '會議與變更', exact: true }).click();
  await page.locator('#add-meeting').click();
  await page.locator('[data-field="topic"]').fill('<img src=x onerror="window.__xss=1">');
  await page.reload();
  expect(await page.evaluate(() => window.__xss)).toBeUndefined();
  await page.getByRole('button', { name: '會議與變更', exact: true }).click();
  await expect(page.locator('[data-field="topic"]')).toHaveValue('<img src=x onerror="window.__xss=1">');
});

test('imported answers remain visible and correction is an append-only draft', async ({ page }) => {
  const fixture = fs.mkdtempSync(path.join(os.tmpdir(), 'owner-records-qa-'));
  for (const file of ['inputs/project.json', 'inputs/requirements.json', 'inputs/planning-register.json', 'inputs/physical-items.json', 'inputs/furniture-layout.json', 'structured/room_program.json', 'inputs/dimensions.json']) {
    const target = path.join(fixture, file);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.copyFileSync(path.join(root, file), target);
  }
  const workspace = JSON.parse(fs.readFileSync(path.join(output, 'owner-workspace.json'), 'utf8'));
  const file = path.join(fixture, 'test-draft.json');
  fs.writeFileSync(file, JSON.stringify({ schema: 'house-owner-draft-v1', project_id: workspace.project_id, source_hashes: workspace.source_hashes, record_hash: workspace.record_hash, rows: [{ id: 'TEST-record-1', kind: 'answer', target: 'PLAN-HOUSEHOLD-01', data: { answer: 'TEST ONLY / 已保存家庭討論' } }] }));
  const python = path.join(root, '.venv/bin/python');
  execFileSync(python, ['-m', 'house_design', 'intake', 'owner-records-import', '--root', fixture, '--file', file, '--apply'], { cwd: root });
  execFileSync(python, ['-m', 'house_design', 'predesign', 'owner-workspace', '--root', fixture], { cwd: root });
  await page.goto(pathToFileURL(path.join(fixture, 'structured/predesign/owner-workspace.html')).href);
  page.on('dialog', dialog => dialog.accept());
  await expect(page.locator('#answer-list article:visible').first()).toContainText('已有匯入回覆');
  await page.locator('#answer-list article:visible').first().getByText('最近已匯入回覆').click();
  await expect(page.locator('#answer-list article:visible').first()).toContainText('已保存家庭討論');
  await page.getByRole('button', { name: '已匯入紀錄', exact: true }).click();
  await page.getByRole('button', { name: '新增修正草稿', exact: true }).click();
  await page.locator('#meeting-list [data-field="answer"]').fill('TEST ONLY / 新增修正');
  const pending = page.waitForEvent('download');
  await page.locator('#download').click();
  const download = await pending;
  const correction = path.join(fixture, 'correction.json');
  await download.saveAs(correction);
  const exported = JSON.parse(fs.readFileSync(correction, 'utf8'));
  expect(exported.rows).toHaveLength(1);
  expect(exported.rows[0].supersedes).toBe('TEST-record-1');
  const preview = JSON.parse(execFileSync(python, ['-m', 'house_design', 'intake', 'owner-records-import', '--root', fixture, '--file', correction], { cwd: root, encoding: 'utf8' }));
  expect(preview.count).toBe(1);
  expect(JSON.parse(fs.readFileSync(path.join(fixture, 'inputs/owner-records.json'), 'utf8')).entries).toHaveLength(1);
});
